<h1>Risultato della Chiamata Generale Articoli</h1>
<?php /*
<p>Qui si hanno solo codice attributi select e vari e se deve essere in vendita. Non ci sono i prezzi e qta</p>
<div>
    <h2>Conteggio degli Articoli: <?php echo $block->getData('conto_articoli'); ?></h2>
    <h2>Articoli rielaborati:</h2>
    <pre><?php print_r($block->getData('articoli_rielaborati')); ?></pre>
    */ ?>
    <h2>Articoli ricevuti:</h2>
    <pre><?php print_r($block->getData('articoli')); ?></pre>
    <?php /*
    <h2>Array ID etichette attributi:</h2>
    <pre><?php print_r($block->getData('id_etichetta')); ?></pre>
</div>
*/ ?>
