<?php
// Decodifica il JSON per assicurarti che sia un array o oggetto PHP
//$responseData = json_decode($response, true);

// era solo un test, non e' piu un json adesso
// Ricodifica il JSON in formato leggibile con indentazione
//$prettyResponse = json_encode($responseData, JSON_PRETTY_PRINT);
//echo htmlspecialchars($prettyResponse, ENT_QUOTES, 'UTF-8');
?>

<h1>Risultato della Chiamata Progressivi Articoli</h1>
<div>
    <h2>Conteggio degli Articoli: <?php echo $block->getData('conto_articoli'); ?></h2>
    <pre><?php print_r($block->getData('codice_qta')); ?></pre>
</div>

